apiVersion: v1
kind: Secret
metadata:
  name: {{ include "yzbfp.handtenpay.tls" . | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if (.Files.Glob "files/bfp-rsa.key") }}
  {{ (.Files.Glob "files/bfp-rsa.key").AsConfig | nindent 2 }}
  {{- end }}
  {{- if (.Files.Glob "files/handtenpay.pub") }}
  {{ (.Files.Glob "files/handtenpay.pub").AsConfig | nindent 2 }}
  {{- end }}
