apiVersion: v1
kind: Secret
metadata:
  name: {{ include "yzbfp.handtenpay" . | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  handtenpay-url: {{ .Values.xdfHandtenpay.baseUrl | b64enc | quote }}
  mq-host: {{ .Values.xdfHandtenpay.messageQueue.host | b64enc | quote }}
  mq-port: {{ .Values.xdfHandtenpay.messageQueue.port | toString | b64enc | quote }}
  mq-username: {{ .Values.xdfHandtenpay.messageQueue.username | b64enc | quote }}
  mq-password: {{ .Values.xdfHandtenpay.messageQueue.password | b64enc | quote }}
  mq-virtual-host: {{ .Values.xdfHandtenpay.messageQueue.virtualHost | b64enc | quote }}
  ftp-ip: {{ .Values.xdfHandtenpay.ftp.ip | b64enc | quote }}
  ftp-port: {{ .Values.xdfHandtenpay.ftp.port | toString | b64enc | quote }}
  ftp-username: {{ .Values.xdfHandtenpay.ftp.username | b64enc | quote }}
  ftp-password: {{ .Values.xdfHandtenpay.ftp.password | b64enc | quote }}
  ftp-catalogue: {{ .Values.xdfHandtenpay.ftp.catalogue | b64enc | quote }}
