annotations:
  category: BFP
apiVersion: v2
appVersion: 2.0.20220211
dependencies:
  - name: common
    repository: https://ferren.github.io/inair-helm-charts/
    version: 1.x.x
description: YZ bfp risk Bairong.
engine: gotpl
home: https://www.incosten.com/
icon: https://www.incosten.com/_nuxt/img/logo.a9cdf55.svg
keywords:
  - bfp
  - crm
  - www
  - http
  - web
maintainers:
  - email: ferrenliu@163.com
    name: FerrenLiu
name: risk-bairong
sources:
  - https://codeup.aliyun.com/61bd3e98fa282c88e103b306/java/bfp-admin2.0-dev
  - https://www.incosten.com/
version: 0.2.2
