spring:
  application:
    name: service-bfp-repay
  datasource:
    url: 
    username: 
    password: 
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-test-query: SELECT 1
      validation-timeout: 250
      minimum-idle: 5
      auto-commit: true
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 500000 #不小于30s 否则会回到默认的1800秒
      maximum-pool-size: 15
      pool-name: DatebookHikariCP
  redis:
    database: 0
    host: 
    port: 6379  #单实例redis用这个配置
    password: 
    timeout: 5000ms
    lettuce:
      pool:
        max-active: 100
        max-wait: 15000ms
        min-idle: 5
dubbo:
  registry:
    address: 
  protocol:
    port: 20884
    name: dubbo
  application:
    name: service-bfp-repay
    qos:
      enable: false
      accept:
        foreign:
          ip: false
  scan:
    basePackages: com.yzbfp.admin.repay.service
  provider:
    timeout: 8000
service:
  version: 2.0
server:
  port: 9004
mybatis-plus:
  #如果是放在java下 classpath:/yourpackage/mapper/*Mapper.xml  如果是resource classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/com/yzbfp/admin/common/mapper/*Mapper.xml
  #多个package用逗号或者分号分隔
  typeAliasesPackage: com.yzbfp.admin.common.pojo
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    cache-enabled: false
  global-config:
    banner: false
    db-config:
      db-type: mysql
repay:
  helipay:
    customerNumber: 
    signKey: 
    publicKey: 
    privateKey: 
    notifyUrl: http://10.10.66.154:30001/repay/notify/helipay/df
    transfer: Transfer
    transferQuery: TransferQuery