server:
  port: 8005
spring:
  redis:
    normal:
       hostname: ${REDIS_HOST:localhost}
       password: ${REDIS_PASSWORD:}
       port: ${REDIS_PORT:6379}
       database: 1
       lettuce:
         pool:
           max-active: 300
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST:pgm-wz91225tvzgk16yj1o.pg.rds.aliyuncs.com}:${POSTGRESQL_PORT:5432}/${POSTGRESQL_DB:gscs_dev}?useUnicode=true&characterEncoding=utf8
    username: gscs_sa
    password: 9ygPGkyM
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    filters: stat
    maxActive: 120
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 120

    druid:
      filter:
        slf4j:
          enabled: true
          statement-create-after-log-enabled: false
          statement-log-enabled: false
          statement-executable-sql-log-enable: true
          statement-log-error-enabled: true
          result-set-log-enabled: false

  jpa:
    hibernate:
      naming: 
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database: mysql
    properties:
      javax.persistence.validation.mode: none
      hibernate:
#        default_schema: ppppp
        show_sql: true
        format_sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  freemarker:
    templateLoaderPath:
      - classpath:/freemarker/templates/
    suffix: .html
email:
  from: yuecai-op@funyard-hotels.com
  host: mail.funyard-hotels.com
  username: yuecai-op@funyard-hotels.com
  password: bgy2021@
  smtp:
    port: 25
logging.path: ./logs
static.path: ./uploadfiles
storableobject:
  filesystem:
    root:  ./uploadfiles
    urlPath: /files
    domain:
app:
  security:
    loginCaptchaEnabled: false
    superPassword: 123456
xcode:
  view_cache_enabled: false
  dev:
    autoConfigEnabled: false
  repository:
    show_sql: true
  emd:
    path: ./src/main/resources/emd