annotations:
  category: CRM
apiVersion: v2
appVersion: 16.0.20230625
dependencies:
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 12.x.x
  - condition: redis.enabled
    name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 17.x.x
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x
description: Odoo is an open source ERP and CRM platform, formerly known as OpenERP, that can connect a wide variety of business operations such as sales, supply chain, finance, and project management.
engine: gotpl
home: https://github.com/ferren/inair-helm-charts/tree/master/inair/odoo
icon: https://bitnami.com/assets/stacks/odoo/img/odoo-stack-220x234.png
keywords:
  - odoo
  - crm
  - www
  - http
  - web
maintainers:
  - email: ferrenliu@163.com
    name: FerrenLiu
name: odoo
sources:
  - https://codeup.aliyun.com/inair/odoo-docker.git
  - https://www.odoo.com/
version: 2.1.9
